// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiziQNd6qr5I46zhDY2y20qw9gS6uW1wY',
    appId: '1:544240971254:web:4f0fe35be1925085d9abd7',
    messagingSenderId: '544240971254',
    projectId: 'campusbuddy-63d7c',
    authDomain: 'campusbuddy-63d7c.firebaseapp.com',
    storageBucket: 'campusbuddy-63d7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiziQNd6qr5I46zhDY2y20qw9gS6uW1wY',
    appId: '1:544240971254:android:4f0fe35be1925085d9abd7',
    messagingSenderId: '544240971254',
    projectId: 'campusbuddy-63d7c',
    storageBucket: 'campusbuddy-63d7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiziQNd6qr5I46zhDY2y20qw9gS6uW1wY',
    appId: '1:544240971254:ios:4f0fe35be1925085d9abd7',
    messagingSenderId: '544240971254',
    projectId: 'campusbuddy-63d7c',
    storageBucket: 'campusbuddy-63d7c.firebasestorage.app',
    iosClientId:
        '544240971254-l01phmn36e0m81aqk9ij5j0so2e22qr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiziQNd6qr5I46zhDY2y20qw9gS6uW1wY',
    appId: '1:544240971254:ios:4f0fe35be1925085d9abd7',
    messagingSenderId: '544240971254',
    projectId: 'campusbuddy-63d7c',
    storageBucket: 'campusbuddy-63d7c.firebasestorage.app',
    iosClientId:
        '544240971254-l01phmn36e0m81aqk9ij5j0so2e22qr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusBuddy',
  );
}
